// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameAddress = "address"

// Address mapped from table <address>
type Address struct {
	ID         int64          `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	UID        int64          `gorm:"column:uid;type:int(10) unsigned;not null" json:"uid"`
	Province   string         `gorm:"column:province;type:varchar(20);not null" json:"province"`
	City       string         `gorm:"column:city;type:varchar(20);not null" json:"city"`
	UpdateTime int64          `gorm:"column:update_time;type:int(10) unsigned;not null" json:"update_time"`
	CreateTime int64          `gorm:"column:create_time;type: int unsigned;not null;autoUpdateTime" json:"create_time"`
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time;type:int(10) unsigned;not null" json:"delete_time"`
	User       User           `gorm:"foreignKey:Address;references:ID" json:"user"`
}

// TableName Address's table name
func (*Address) TableName() string {
	return TableNameAddress
}
